"""Loader for the precomputed default analysis runs (real pipeline outputs,
generated by scripts/build_default_runs.py). Pages show these by default so a
reviewer sees a full analysis without running anything -- and can still run a
fresh live call, which overrides the default for that session.
"""

from __future__ import annotations

import json
import os

_DIR = os.path.join(os.path.dirname(__file__), "default_runs")


def load_default(name: str) -> tuple[dict | None, list]:
    """Return (result, transcript) for a saved default run, or (None, []) if
    none has been generated yet."""
    path = os.path.join(_DIR, f"{name}.json")
    if not os.path.exists(path):
        return None, []
    with open(path, encoding="utf-8") as f:
        payload = json.load(f)
    return payload.get("result"), payload.get("transcript", [])
